version: "3.8"

services:
  jeckyll-server:
    build: .
    environment:
      - MODE_ENV
    ports:
      - "4000:4000"
      - "35729:35729" # порт для LiveReload
    # command: "tail -f /dev/null"
    volumes:
      - ./:/src
