services:
  jeckyll-server:
    environment:
      - MODE_ENV
    env_file:
      - ${ENV:-.env_default} # Значение по умолчанию
    build: .
    ports:
      - "35729:35729"
      - "4000:4000"
    # command: "tail -f /dev/null"
    volumes:
      - ./:/src
