version: "3.8"

services:
  jeckyll-server:
    build: .
    environment:
      - MODE_ENV
    ports:
      - "4000:4000"
    # command: "jekyll serve --watch --host 0.0.0.0"
    # command: "tail -f /dev/null"
    volumes:
      - ./:/src
